### ISSUE TITLE
Apache Jena Fuseki and Virtuoso Incompatibility

### ISSUE THREAD

**Issue by kidehen** [Bayer-Group/COLID-Documentation#1]
Wondering if you could provide some examples of Apache Jena Fuseki and Virtuoso incompatibilities. I am keen to test this system using Virtuoso solely for the following:

1. SPARQL & Graph Database Functionality
2. SQL & conventional RDBMS Functionality 
3. Full Text Search and Indexing Functionality
4. Security Functionality

**Comment by lansidev** [comment]
Incompatibilities between Apache Jena Fuseki and OpenLink Virtuoso are currently not known to us. In order to use Amazon Neptune, we had to make minor adjustments to the SPARQL queries, which we have documented [here](https://bayer-group.github.io/COLID-Documentation/#/infrastructure/databases/graph-database?id=amazon-neptune-amp-apache-jena-fuseki). However, these may have been eliminated by Amazon by now.

You are very welcome to test COLID together with OpenLink Virtuoso. In our docker environment, Apache Jena Fuseki is currently in use, which is connected to the Registration Service and the Indexing Crawler Service. Via the `ColidTripleStoreOptions` configuration section of the appsettings.docker.json files [here ](https://github.com/Bayer-Group/COLID-Registration-Service/blob/master/src/COLID.RegistrationService.WebApi/appsettings.Docker.json) and [here](https://github.com/Bayer-Group/COLID-Indexing-Crawler-Service/blob/master/COLID.IndexingCrawlerService.WebApi/appsettings.Docker.json) the query and update connections can be customized.

**Comment by kidehen** [comment]
> Incompatibilities between Apache Jena Fuseki and OpenLink Virtuoso are currently not known to us.

But your README  listed that as the reason for switching to Amazon Neptune. My goal was to look into such incompatibilities. 

Ultimately, we do want to have a go at porting this system to Virtuoso bearing in mind Virtuoso's ability can handling the combined functionality in a single instance:

1. Graph Database (Neptune)
1. Relational Data Services (RDS)
1. Test Search & Indexing (Elastic Search)
1. Identity Management
